/*
 * This source file was generated by the Gradle 'init' task
 */

import io.osipxd.issue.ktypenull.checkNullabilityInconsistency
import org.junit.jupiter.api.Assertions.assertFalse
import kotlin.test.Test

class NullabilityInconsistencyTest {
    @Test
    fun `test nullability inconsistency`() {
        assertFalse(checkNullabilityInconsistency<String>()) { "type should be either equal to null or not" }
    }
}
